// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: syncpb/ip_sync.proto

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IpSyncService_ReportInterface_FullMethodName  = "/sync.v1.IpSyncService/ReportInterface"
	IpSyncService_ReleaseInterface_FullMethodName = "/sync.v1.IpSyncService/ReleaseInterface"
	IpSyncService_GetStatus_FullMethodName        = "/sync.v1.IpSyncService/GetStatus"
)

// IpSyncServiceClient is the client API for IpSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpSyncServiceClient interface {
	ReportInterface(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	ReleaseInterface(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type ipSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIpSyncServiceClient(cc grpc.ClientConnInterface) IpSyncServiceClient {
	return &ipSyncServiceClient{cc}
}

func (c *ipSyncServiceClient) ReportInterface(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, IpSyncService_ReportInterface_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipSyncServiceClient) ReleaseInterface(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, IpSyncService_ReleaseInterface_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipSyncServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, IpSyncService_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpSyncServiceServer is the server API for IpSyncService service.
// All implementations must embed UnimplementedIpSyncServiceServer
// for forward compatibility
type IpSyncServiceServer interface {
	ReportInterface(context.Context, *ReportRequest) (*ReportResponse, error)
	ReleaseInterface(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedIpSyncServiceServer()
}

// UnimplementedIpSyncServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIpSyncServiceServer struct {
}

func (UnimplementedIpSyncServiceServer) ReportInterface(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportInterface not implemented")
}
func (UnimplementedIpSyncServiceServer) ReleaseInterface(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseInterface not implemented")
}
func (UnimplementedIpSyncServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedIpSyncServiceServer) mustEmbedUnimplementedIpSyncServiceServer() {}

// UnsafeIpSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpSyncServiceServer will
// result in compilation errors.
type UnsafeIpSyncServiceServer interface {
	mustEmbedUnimplementedIpSyncServiceServer()
}

func RegisterIpSyncServiceServer(s grpc.ServiceRegistrar, srv IpSyncServiceServer) {
	s.RegisterService(&IpSyncService_ServiceDesc, srv)
}

func _IpSyncService_ReportInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpSyncServiceServer).ReportInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpSyncService_ReportInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpSyncServiceServer).ReportInterface(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpSyncService_ReleaseInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpSyncServiceServer).ReleaseInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpSyncService_ReleaseInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpSyncServiceServer).ReleaseInterface(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpSyncService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpSyncServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpSyncService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpSyncServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpSyncService_ServiceDesc is the grpc.ServiceDesc for IpSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.v1.IpSyncService",
	HandlerType: (*IpSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportInterface",
			Handler:    _IpSyncService_ReportInterface_Handler,
		},
		{
			MethodName: "ReleaseInterface",
			Handler:    _IpSyncService_ReleaseInterface_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _IpSyncService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncpb/ip_sync.proto",
}
